# Generated by Django 3.2.9 on 2022-01-18 07:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pictdata', '0002_auto_20220118_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomQuestionModel',
            fields=[
                ('question', models.CharField(max_length=100)),
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
