# Generated by Django 3.2.9 on 2022-01-19 06:13

from django.db import migrations, models
import pictdata.models


class Migration(migrations.Migration):

    dependencies = [
        ('pictdata', '0004_alter_pictdatamodel_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictdatamodel',
            name='picture',
            field=models.ImageField(upload_to=pictdata.models.image_directory_path),
        ),
    ]
