# Generated by Django 3.2.9 on 2022-01-20 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictdata', '0005_alter_pictdatamodel_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='randomquestionmodel',
            old_name='ID',
            new_name='id',
        ),
    ]
