# Generated by Django 3.2.9 on 2022-01-21 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pictdata', '0006_rename_id_randomquestionmodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomquestionmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser'),
            preserve_default=False,
        ),
    ]
