# Generated by Django 3.2.9 on 2022-01-21 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictdata', '0007_randomquestionmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='randomquestionmodel',
            name='user',
        ),
    ]
